import ContentMenu from "../ContentMenu"
import Intro from "../Intro"
import Header from "../components/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <Header/>
      <Intro/>
      <ContentMenu/>
      <div style={{ backgroundImage: "url('https://avatars.mds.yandex.net/i?id=2954b72a8da82a2d6e2e38b556900b066ce5aeab-9147982-images-thumbs&n=13')", backgroundSize: 'cover', backgroundRepeat: 'no-repeat', backgroundPosition: 'center' }}  className='  bg-blgreen-200 '>{children}</div>
    </html>
  )
}
